name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.0.5
        with:
          base_uri: https://eu.ast.checkmarx.net
          cx_tenant: nfr_redshift_nfr
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          project_name: DemoWebViewGoat-master01
          branch: ${{ github.ref }}
          additional_params: --tags test1,test2 --scan-types sast,kics,sca
